# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = تم استلام الملفات

file-received-mess-with-contact =
    { $senderName } أرسل الملف "{ $fileName }" بحجم { $fileSizeValue } { $fileSizeUnit } عبر "{ $requestName }"

file-received-title = تم استلام الملف

received-file-via-filerequest =
    تم استلام الملف "{ $fileName }" بحجم { $fileSizeValue } { $fileSizeUnit } من مرسل غير معروف عبر "{ $requestName }"

service-channel-name = استمرارية الخدمة

service-persistent-running = يجب أن يبقى Fyles قيد التشغيل لإرسال واستقبال الملفات في أي وقت

service-persistent-starting = فايليس يبدأ التشغيل

service-persistent-title = فيلس قيد التشغيل

service-persistent-waiting-storage = في انتظار إعداد دليل التخزين...

