# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Получени файлове

file-received-mess-with-contact =
    { $senderName } изпрати файл "{ $fileName }" с размер { $fileSizeValue } { $fileSizeUnit } чрез "{ $requestName }"

file-received-title = Получен файл

received-file-via-filerequest =
    Получен файл "{ $fileName }" с размер { $fileSizeValue } { $fileSizeUnit } от неизвестен подател чрез "{ $requestName }"

service-channel-name = Устойчивост на услугата

service-persistent-running =
    Fyles трябва да продължи да работи, за да може да изпраща и получава файлове по всяко време

service-persistent-starting = Fyles се стартира

service-persistent-title = Fyles работи

service-persistent-waiting-storage = Изчакване на настройка на директорията за съхранение...

