# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Přijaté soubory

file-received-mess-with-contact =
    { $senderName } poslal soubor "{ $fileName }" o velikosti { $fileSizeValue } { $fileSizeUnit } přes "{ $requestName }"

file-received-title = Soubor přijat

received-file-via-filerequest =
    Přijatý soubor "{ $fileName }" o velikosti { $fileSizeValue } { $fileSizeUnit } od neznámého odesílatele prostřednictvím "{ $requestName }"

service-channel-name = Trvalá služba

service-persistent-running = Fyles musí být spuštěn, aby mohl kdykoli odesílat a přijímat soubory.

service-persistent-starting = Fyles se spouští

service-persistent-title = Fyles běží

service-persistent-waiting-storage = Čekám na nastavení adresáře pro úložiště...

