# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Modtagne filer

file-received-mess-with-contact =
    { $senderName } sendte filen "{ $fileName }" på størrelse med { $fileSizeValue } { $fileSizeUnit } via "{ $requestName }"

file-received-title = Fil modtaget

received-file-via-filerequest =
    Modtaget fil "{ $fileName }" af størrelse { $fileSizeValue } { $fileSizeUnit } fra en ukendt afsender via "{ $requestName }"

service-channel-name = Tjeneste vedvarende

service-persistent-running = Fyles skal holdes kørende for at sende og modtage filer når som helst

service-persistent-starting = Fyles starter op

service-persistent-title = Fyles kører

service-persistent-waiting-storage = Venter på opsætning af lagermappe...

