# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Empfangene Dateien

file-received-mess-with-contact =
    { $senderName } hat die Datei "{ $fileName }" mit einer Größe von { $fileSizeValue } { $fileSizeUnit } über "{ $requestName }" gesendet

file-received-title = Datei empfangen

received-file-via-filerequest =
    Datei "{ $fileName }" mit einer Größe von { $fileSizeValue } { $fileSizeUnit } von einem unbekannten Absender über "{ $requestName }" erhalten

service-channel-name = Dienst im Hintergrund

service-persistent-running =
    Fyles muss im Hintergrund laufen, um jederzeit Dateien zu senden und zu empfangen

service-persistent-starting = Fyles wird gestartet

service-persistent-title = Fyles läuft

service-persistent-waiting-storage = Warte auf Einrichtung des Speicherordners …

