# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Ληφθέντα αρχεία

file-received-mess-with-contact =
    { $senderName } έστειλε το αρχείο "{ $fileName }" μεγέθους { $fileSizeValue } { $fileSizeUnit } μέσω του "{ $requestName }"

file-received-title = Λήφθηκε αρχείο

received-file-via-filerequest =
    Λάβατε το αρχείο "{ $fileName }" μεγέθους { $fileSizeValue } { $fileSizeUnit } από άγνωστο αποστολέα μέσω του "{ $requestName }"

service-channel-name = Διαρκής Υπηρεσία

service-persistent-running =
    Η Fyles πρέπει να παραμείνει ενεργή για να στέλνει και να λαμβάνει αρχεία οποιαδήποτε στιγμή

service-persistent-starting = Το Fyles ξεκινά

service-persistent-title = Fyles σε εκτέλεση

service-persistent-waiting-storage = Αναμονή για ρύθμιση του καταλόγου αποθήκευσης...

