# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Received files

file-received-mess-with-contact =
    { $senderName } sent file "{ $fileName }" of size { $fileSizeValue } { $fileSizeUnit } via "{ $requestName }"

file-received-title = File received

received-file-via-filerequest =
    Received file "{ $fileName }" of size { $fileSizeValue } { $fileSizeUnit } from an unknown sender via "{ $requestName }"

service-channel-name = Service Persistence

service-persistent-running = Fyles needs to be kept running to send and receive files at any time

service-persistent-starting = Fyles starting up

service-persistent-title = Fyles running

service-persistent-waiting-storage = Waiting for storage directory setup...

