# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Archivos recibidos

file-received-mess-with-contact =
    { $senderName } envió el archivo "{ $fileName }" de tamaño { $fileSizeValue } { $fileSizeUnit } a través de "{ $requestName }"

file-received-title = Archivo recibido

received-file-via-filerequest =
    Archivo "{ $fileName }" recibido de tamaño { $fileSizeValue } { $fileSizeUnit } de un remitente desconocido a través de "{ $requestName }"

service-channel-name = Persistencia del servicio

service-persistent-running =
    Fyles necesita seguir ejecutándose para enviar y recibir archivos en cualquier momento

service-persistent-starting = Fyles iniciando

service-persistent-title = Fyles en ejecución

service-persistent-waiting-storage = Esperando la configuración del directorio de almacenamiento...

