# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Saadud failid

file-received-mess-with-contact =
    { $senderName } saatis faili "{ $fileName }" suurusega { $fileSizeValue } { $fileSizeUnit } kaudu "{ $requestName }"

file-received-title = Fail saadud

received-file-via-filerequest =
    Saadi fail "{ $fileName }" suurusega { $fileSizeValue } { $fileSizeUnit } tundmatult saatjalt läbi "{ $requestName }"

service-channel-name = Teenuse püsivus

service-persistent-running = Fyles peab olema pidevalt käimas, et saata ja vastu võtta faile igal ajal

service-persistent-starting = Fyles käivitub

service-persistent-title = Fyles töötab

service-persistent-waiting-storage = Ootan salvestuskausta seadistamist...

