# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Vastaanotetut tiedostot

file-received-mess-with-contact =
    { $senderName } lähetti tiedoston "{ $fileName }" koossa { $fileSizeValue } { $fileSizeUnit } käyttäen "{ $requestName }"

file-received-title = Tiedosto vastaanotettu

received-file-via-filerequest =
    Saapunut tiedosto "{ $fileName }" kooltaan { $fileSizeValue } { $fileSizeUnit } tuntemattomalta lähettäjältä kautta "{ $requestName }"

service-channel-name = Palvelun kestävyys

service-persistent-running =
    Fylesin on pysyttävä käynnissä, jotta tiedostojen lähettäminen ja vastaanottaminen on mahdollista milloin tahansa.

service-persistent-starting = Fyles käynnistyy

service-persistent-title = Fyles käynnissä

service-persistent-waiting-storage = Odotetaan tallennushakemiston asetusta...

