# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Fichiers reçus

file-received-mess-with-contact =
    { $senderName } a envoyé le fichier "{ $fileName }" de taille { $fileSizeValue } { $fileSizeUnit } via "{ $requestName }"

file-received-title = Fichier reçu

received-file-via-filerequest =
    Fichier "{ $fileName }" de taille { $fileSizeValue } { $fileSizeUnit } reçu d'un expéditeur inconnu via "{ $requestName }"

service-channel-name = Persistance du service

service-persistent-running =
    Fyles doit rester en cours d'exécution pour envoyer et recevoir des fichiers à tout moment

service-persistent-starting = Fyles en cours de démarrage

service-persistent-title = Fyles en cours d'exécution

service-persistent-waiting-storage = En attente de la configuration du répertoire de stockage...

