# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Comhoibriú comhoibrithe

file-received-mess-with-contact =
    { $senderName } chuir comhoibriú "{ $requestName }" ar fáil le comhad "{ $fileName }" le méid { $fileSizeValue } { $fileSizeUnit }

file-received-title = Comhoibriú comhoibriúcháin

received-file-via-filerequest =
    Fuair an comhad "{ $fileName }" le méid { $fileSizeValue } { $fileSizeUnit } ó sheoltar anaithnid trí "{ $requestName }"

service-channel-name = Seirbhís Inmharthanachta

service-persistent-running =
    Teastaíonn go gcoimeádfaidh Fyles ag rith chun comhoibriú agus a fháil comhoibriú ag am ar bith.

service-persistent-starting = Fyles ag tosú

service-persistent-title = Fyles ag obair

service-persistent-waiting-storage = Ag súil le socrú an chórais stórála...

