# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = प्राप्त फ़ाइलें

file-received-mess-with-contact =
    { $senderName } ने "{ $requestName }" के माध्यम से "{ $fileName }" फ़ाइल भेजी है, जिसका आकार { $fileSizeValue } { $fileSizeUnit } है।

file-received-title = फाइल प्राप्त हुई

received-file-via-filerequest =
    अज्ञात प्रेषक से "{ $requestName }" के माध्यम से प्राप्त फ़ाइल "{ $fileName }" का आकार { $fileSizeValue } { $fileSizeUnit } है।

service-channel-name = सेवा स्थिरता

service-persistent-running = Fyles को फ़ाइलों को भेजने और प्राप्त करने के लिए हमेशा चलाना आवश्यक है

service-persistent-starting = Fyles शुरू हो रहा है

service-persistent-title = Fyles चल रहा है

service-persistent-waiting-storage = स्टोरेज डायरेक्टरी सेटअप का इंतज़ार कर रहे हैं...

