# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Primljeni datoteke

file-received-mess-with-contact =
    { $senderName } je poslao datoteku "{ $fileName }" veličine { $fileSizeValue } { $fileSizeUnit } putem "{ $requestName }"

file-received-title = Datoteka primljena

received-file-via-filerequest =
    Primljen je fajl "{ $fileName }" veličine { $fileSizeValue } { $fileSizeUnit } od nepoznatog pošiljaoca putem "{ $requestName }"

service-channel-name = Trajanje usluge

service-persistent-running =
    Fyles mora ostati pokrenut kako bi mogao slati i primati datoteke u bilo kojem trenutku

service-persistent-starting = Fyles se pokreće

service-persistent-title = Fyles radi

service-persistent-waiting-storage = Čekanje na postavljanje direktorija za pohranu...

