# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Kapott fájlok

file-received-mess-with-contact =
    { $senderName } küldött egy "{ $fileName }" nevű fájlt, amelynek mérete { $fileSizeValue } { $fileSizeUnit } a(z) "{ $requestName }" szolgáltatáson keresztül

file-received-title = Fájl érkezett

received-file-via-filerequest =
    Ismertlen küldőtől érkezett "{ $fileName }" fájl, mérete { $fileSizeValue } { $fileSizeUnit } a(z) "{ $requestName }" alkalmazáson keresztül.

service-channel-name = Szolgáltatás tartóssága

service-persistent-running =
    A Fyles-t folyamatosan futtatni kell a fájlok bármikor történő küldéséhez és fogadásához.

service-persistent-starting = A Fyles elindul

service-persistent-title = Fyles fut a háttérben

service-persistent-waiting-storage = Várakozás a tárolási könyvtár beállítására...

