# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = File diterima

file-received-mess-with-contact =
    { $senderName } mengirim file "{ $fileName }" dengan ukuran { $fileSizeValue } { $fileSizeUnit } melalui "{ $requestName }"

file-received-title = Berkas diterima

received-file-via-filerequest =
    File "{ $fileName }" diterima dengan ukuran { $fileSizeValue } { $fileSizeUnit } dari pengirim yang tidak dikenal melalui "{ $requestName }"

service-channel-name = Ketahanan Layanan

service-persistent-running = Fyles perlu tetap berjalan untuk mengirim dan menerima file kapan saja

service-persistent-starting = Fyles sedang dimulai

service-persistent-title = Fyles berjalan

service-persistent-waiting-storage = Menunggu pengaturan direktori penyimpanan...

