# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Móttökufailar

file-received-mess-with-contact =
    { $senderName } sendi skrá "{ $fileName }" að stærð { $fileSizeValue } { $fileSizeUnit } í gegnum "{ $requestName }"

file-received-title = Skrá received

received-file-via-filerequest =
    Fáður skrá "{ $fileName }" að stærð { $fileSizeValue } { $fileSizeUnit } frá óþekktum sendanda í gegnum "{ $requestName }"

service-channel-name = Þjónusta viðvarandi

service-persistent-running = Fyles þarf að vera í gangi til að senda og taka á móti skrám hvenær sem er

service-persistent-starting = Fyles er að hefjast

service-persistent-title = Fyles í gangi

service-persistent-waiting-storage = Bíðandi eftir uppsetningu á geymsluskrá...

