# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = File ricevuti

file-received-mess-with-contact =
    { $senderName } ha inviato il file "{ $fileName }" di dimensioni { $fileSizeValue } { $fileSizeUnit } tramite "{ $requestName }"

file-received-title = File ricevuto

received-file-via-filerequest =
    File "{ $fileName }" ricevuto di dimensioni { $fileSizeValue } { $fileSizeUnit } da un mittente sconosciuto tramite "{ $requestName }"

service-channel-name = Persistenza del servizio

service-persistent-running = Fyles deve rimanere attivo per inviare e ricevere file in qualsiasi momento

service-persistent-starting = Fyles in avvio

service-persistent-title = Fyles in esecuzione

service-persistent-waiting-storage = In attesa della configurazione della directory di archiviazione...

