# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = 受信したファイル

file-received-mess-with-contact =
    { $senderName }が"{ $fileName }"のサイズ{ $fileSizeValue } { $fileSizeUnit }のファイルを"{ $requestName }"経由で送信しました

file-received-title = ファイルを受信しました

received-file-via-filerequest =
    "{ $requestName }"を介して不明な送信者からサイズ{ $fileSizeValue } { $fileSizeUnit }のファイル"{ $fileName }"を受信しました

service-channel-name = サービスの永続性

service-persistent-running = Fylesは、いつでもファイルを送受信するために実行を維持する必要があります

service-persistent-starting = Fylesを起動中

service-persistent-title = Fylesが実行中です

service-persistent-waiting-storage = ストレージディレクトリの設定を待機中...

