# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = 파일 수신됨

file-received-mess-with-contact =
    { $senderName }이 "{ $requestName }"를 통해 크기 { $fileSizeValue } { $fileSizeUnit }의 파일 "{ $fileName }"을 보냈습니다.

file-received-title = 파일 수신됨

received-file-via-filerequest =
    알 수 없는 발신자로부터 "{ $requestName }"를 통해 크기 { $fileSizeValue } { $fileSizeUnit }의 파일 "{ $fileName }"을(를) 받았습니다.

service-channel-name = 서비스 지속성

service-persistent-running = Fyles는 언제든지 파일을 전송하고 수신하기 위해 계속 실행되어야 합니다.

service-persistent-starting = Fyles 시작 중

service-persistent-title = Fyles 실행 중

service-persistent-waiting-storage = 저장소 디렉토리 설정 대기 중...

