# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Gauti failai

file-received-mess-with-contact =
    { $senderName } atsiuntė failą "{ $fileName }" dydžiu { $fileSizeValue } { $fileSizeUnit } per "{ $requestName }"

file-received-title = Gautas failas

received-file-via-filerequest =
    Gautas failas "{ $fileName }" dydžio { $fileSizeValue } { $fileSizeUnit } iš nežinomo siuntėjo per "{ $requestName }"

service-channel-name = Paslaugos nuolatinumas

service-persistent-running =
    Fyles turi būti nuolat veikiamas, kad bet kada būtų galima siųsti ir gauti failus.

service-persistent-starting = Fyles paleidžiamas

service-persistent-title = Fyles veikia

service-persistent-waiting-storage = Laukiama, kol bus sukonfigūruota saugyklos direktorija...

