# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Saņemtie faili

file-received-mess-with-contact =
    { $senderName } nosūtīja failu "{ $fileName }" ar izmēru { $fileSizeValue } { $fileSizeUnit } caur "{ $requestName }"

file-received-title = Fails saņemts

received-file-via-filerequest =
    Saņemts fails "{ $fileName }" ar izmēru { $fileSizeValue } { $fileSizeUnit } no nezināma sūtītāja caur "{ $requestName }"

service-channel-name = Pakalpojuma noturība

service-persistent-running = Fyles jābūt aktīvam, lai jebkurā laikā varētu sūtīt un saņemt failus

service-persistent-starting = Fyles tiek iedarbināts

service-persistent-title = Fyles darbojas

service-persistent-waiting-storage = Gaidām, kamēr tiks iestatīta krātuves direktorija...

