# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Fajlovi primljeni

file-received-mess-with-contact =
    { $senderName } ka "{ $fileName }" faylını { $fileSizeValue } { $fileSizeUnit } ölçüsünde "{ $requestName }" vasitəsilə göndərdi

file-received-title = Fajl i pranuar

received-file-via-filerequest =
    Pr menerima file "{ $fileName }" berukuran { $fileSizeValue } { $fileSizeUnit } dari pengirim yang tidak dikenal melalui "{ $requestName }"

service-channel-name = Përhershmëria e Shërbimit

service-persistent-running = Fyles duhet të mbetet në funksionim për të dërguar dhe marrë skedarë në çdo kohë

service-persistent-starting = Fyles se poçinjanjem

service-persistent-title = Fyles në funksion

service-persistent-waiting-storage = Počekujem na postavljanje direktorija za skladištenje...

