# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Fajli reçevu

file-received-mess-with-contact =
    { $senderName } je poslal datoteko "{ $fileName }" velikosti { $fileSizeValue } { $fileSizeUnit } preko "{ $requestName }"

file-received-title = Fajl prejet

received-file-via-filerequest =
    Fajl "{ $fileName }" primljen veličine { $fileSizeValue } { $fileSizeUnit } od nepoznatog pošiljaoca putem "{ $requestName }"

service-channel-name = Pervasivnost storitve

service-persistent-running =
    Fyles je treba ohraniti v teku, da lahko kadar koli pošiljate in prejemate datoteke

service-persistent-starting = Fyles se začenja

service-persistent-title = Fyles正在运行

service-persistent-waiting-storage = A naghanta para sa pag-set up ng direktoryo ng imbakan...

