# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Mottatte filer

file-received-mess-with-contact =
    { $senderName } sendte filen "{ $fileName }" på størrelse med { $fileSizeValue } { $fileSizeUnit } via "{ $requestName }"

file-received-title = Fil mottatt

received-file-via-filerequest =
    Mottatt fil "{ $fileName }" av størrelse { $fileSizeValue } { $fileSizeUnit } fra en ukjent avsender via "{ $requestName }"

service-channel-name = Tjenestevedvarende

service-persistent-running = Fyles må holdes kjørende for å sende og motta filer når som helst

service-persistent-starting = Fyles starter opp

service-persistent-title = Fyles kjører

service-persistent-waiting-storage = Venter på oppsett av lagringskatalog...

