# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Ontvangen bestanden

file-received-mess-with-contact =
    { $senderName } heeft het bestand "{ $fileName }" van grootte { $fileSizeValue } { $fileSizeUnit } verzonden via "{ $requestName }"

file-received-title = Bestand ontvangen

received-file-via-filerequest =
    Bestand "{ $fileName }" ontvangen van onbekende afzender met een grootte van { $fileSizeValue } { $fileSizeUnit } via "{ $requestName }"

service-channel-name = Dienstenpersistentie

service-persistent-running =
    Fyles moet actief blijven om op elk moment bestanden te verzenden en te ontvangen

service-persistent-starting = Fyles wordt opgestart

service-persistent-title = Fyles is actief

service-persistent-waiting-storage = Wachten op de configuratie van de opslagmap...

