# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Odebrane pliki

file-received-mess-with-contact =
    { $senderName } wysłał plik "{ $fileName }" o rozmiarze { $fileSizeValue } { $fileSizeUnit } za pośrednictwem "{ $requestName }"

file-received-title = Plik odebrany

received-file-via-filerequest =
    Otrzymano plik "{ $fileName }" o rozmiarze { $fileSizeValue } { $fileSizeUnit } od nieznanego nadawcy za pośrednictwem "{ $requestName }"

service-channel-name = Trwałość usługi

service-persistent-running =
    Fyles musi być uruchomiony, aby móc wysyłać i odbierać pliki w dowolnym momencie.

service-persistent-starting = Fyles uruchamia się

service-persistent-title = Fyles działa

service-persistent-waiting-storage = Oczekiwanie na skonfigurowanie katalogu pamięci...

