# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Arquivos recebidos

file-received-mess-with-contact =
    { $senderName } enviou o arquivo "{ $fileName }" com tamanho { $fileSizeValue } { $fileSizeUnit } via "{ $requestName }"

file-received-title = Arquivo recebido

received-file-via-filerequest =
    Arquivo recebido "{ $fileName }" de tamanho { $fileSizeValue } { $fileSizeUnit } de um remetente desconhecido via "{ $requestName }"

service-channel-name = Persistência do Serviço

service-persistent-running =
    O Fyles precisa continuar em execução para enviar e receber arquivos a qualquer momento.

service-persistent-starting = Fyles iniciando

service-persistent-title = Fyles em execução

service-persistent-waiting-storage = Aguardando a configuração do diretório de armazenamento...

