# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Fișiere primite

file-received-mess-with-contact =
    { $senderName } a trimis fișierul "{ $fileName }" de dimensiune { $fileSizeValue } { $fileSizeUnit } prin "{ $requestName }"

file-received-title = Fișier primit

received-file-via-filerequest =
    Fișier primit "{ $fileName }" de dimensiune { $fileSizeValue } { $fileSizeUnit } de la un expeditor necunoscut prin "{ $requestName }"

service-channel-name = Persistența serviciului

service-persistent-running =
    Fyles trebuie să rămână activ pentru a trimite și a primi fișiere în orice moment

service-persistent-starting = Fyles se pornește

service-persistent-title = Fyles în execuție

service-persistent-waiting-storage = Aștept configurarea directorului de stocare...

