# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Полученные файлы

file-received-mess-with-contact =
    { $senderName } отправил файл "{ $fileName }" размером { $fileSizeValue } { $fileSizeUnit } через "{ $requestName }"

file-received-title = Файл получен

received-file-via-filerequest =
    Получен файл "{ $fileName }" размером { $fileSizeValue } { $fileSizeUnit } от неизвестного отправителя через "{ $requestName }"

service-channel-name = Постоянство сервиса

service-persistent-running =
    Fyles должен продолжать работать, чтобы отправлять и получать файлы в любое время

service-persistent-starting = Fyles запускается

service-persistent-title = Fyles работает

service-persistent-waiting-storage = Ожидание настройки каталога хранения...

