# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Prijaté súbory

file-received-mess-with-contact =
    { $senderName } poslal súbor "{ $fileName }" s veľkosťou { $fileSizeValue } { $fileSizeUnit } cez "{ $requestName }"

file-received-title = Súbor prijatý

received-file-via-filerequest =
    Prijatý súbor "{ $fileName }" s veľkosťou { $fileSizeValue } { $fileSizeUnit } od neznámeho odosielateľa cez "{ $requestName }"

service-channel-name = Trvalá služba

service-persistent-running =
    Fyles musí byť neustále spustený, aby mohol kedykoľvek posielať a prijímať súbory.

service-persistent-starting = Fyles sa spúšťa

service-persistent-title = Fyles beží

service-persistent-waiting-storage = Čakám na nastavenie adresára úložiska...

