# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Prejeti datoteke

file-received-mess-with-contact =
    { $senderName } je poslal datoteko "{ $fileName }" velikosti { $fileSizeValue } { $fileSizeUnit } preko "{ $requestName }"

file-received-title = Datoteka prejeta

received-file-via-filerequest =
    Prejet je bil datoteka "{ $fileName }" velikosti { $fileSizeValue } { $fileSizeUnit } od neznanega pošiljatelja prek "{ $requestName }"

service-channel-name = Vztrajnost storitve

service-persistent-running = Fyles mora ostati v teku, da lahko kadar koli pošilja in prejema datoteke

service-persistent-starting = Fyles se začenja

service-persistent-title = Fyles deluje

service-persistent-waiting-storage = Čakam na nastavitev shranjevanja direktorija...

