# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Skedh të pranuara

file-received-mess-with-contact =
    { $senderName } dërgoi skedarin "{ $fileName }" me madhësi { $fileSizeValue } { $fileSizeUnit } përmes "{ $requestName }"

file-received-title = Skedha e marrë

received-file-via-filerequest =
    Pranuar file "{ $fileName }" me madhësi { $fileSizeValue } { $fileSizeUnit } nga një dërgues i panjohur përmes "{ $requestName }"

service-channel-name = Përshtatja e Shërbimit

service-persistent-running = Fyles duhet të mbetet në funksionim për të dërguar dhe marrë skedarë në çdo kohë

service-persistent-starting = Fyles po fillon

service-persistent-title = Fyles po punon

service-persistent-waiting-storage = Po presin për konfigurimin e drejtorisë së ruajtjes...

