# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Primljeni fajlovi

file-received-mess-with-contact =
    { $senderName } je poslao datoteku "{ $fileName }" veličine { $fileSizeValue } { $fileSizeUnit } putem "{ $requestName }"

file-received-title = Fajl primljen

received-file-via-filerequest =
    Primljen fajl "{ $fileName }" veličine { $fileSizeValue } { $fileSizeUnit } od nepoznatog pošiljaoca putem "{ $requestName }"

service-channel-name = Persistencija usluge

service-persistent-running =
    Fyles mora da bude pokrenut da bi mogao da šalje i prima fajlove u bilo kojem trenutku

service-persistent-starting = Fyles se pokreće

service-persistent-title = Fyles radi

service-persistent-waiting-storage = Čekanje na podešavanje skladišnog direktorijuma...

