# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Mottagna filer

file-received-mess-with-contact =
    { $senderName } skickade filen "{ $fileName }" med storleken { $fileSizeValue } { $fileSizeUnit } via "{ $requestName }"

file-received-title = Fil mottagen

received-file-via-filerequest =
    Mottagen fil "{ $fileName }" av storlek { $fileSizeValue } { $fileSizeUnit } från en okänd avsändare via "{ $requestName }"

service-channel-name = Tjänstepersistens

service-persistent-running = Fyles måste hållas igång för att kunna skicka och ta emot filer när som helst

service-persistent-starting = Fyles startar

service-persistent-title = Fyles körs

service-persistent-waiting-storage = Väntar på att lagringskatalogen ska konfigureras...

