# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Alınan dosyalar

file-received-mess-with-contact =
    { $senderName } "{ $requestName }" üzerinden { $fileSizeValue } { $fileSizeUnit } boyutunda "{ $fileName }" dosyasını gönderdi.

file-received-title = Dosya alındı

received-file-via-filerequest =
    "{ $requestName }" üzerinden bilinmeyen bir gönderen tarafından { $fileSizeValue } { $fileSizeUnit } boyutunda "{ $fileName }" dosyası alındı

service-channel-name = Hizmet Sürekliliği

service-persistent-running =
    Fyles'ın dosya göndermek ve almak için her zaman çalışır durumda kalması gerekiyor

service-persistent-starting = Fyles başlatılıyor

service-persistent-title = Fyles çalışıyor

service-persistent-waiting-storage = Depolama dizini kurulumu bekleniyor...

