# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = Отримані файли

file-received-mess-with-contact =
    { $senderName } надіслав файл "{ $fileName }" розміром { $fileSizeValue } { $fileSizeUnit } через "{ $requestName }"

file-received-title = Файл отримано

received-file-via-filerequest =
    Отримано файл "{ $fileName }" розміром { $fileSizeValue } { $fileSizeUnit } від невідомого відправника через "{ $requestName }"

service-channel-name = Постійність служби

service-persistent-running =
    Fyles має залишатися запущеним, щоб надсилати та отримувати файли в будь-який час

service-persistent-starting = Fyles запускається

service-persistent-title = Fyles працює

service-persistent-waiting-storage = Очікування налаштування каталогу зберігання...

