# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = 接收的文件

file-received-mess-with-contact =
    { $senderName }通过"{ $requestName }"发送了大小为{ $fileSizeValue } { $fileSizeUnit }的文件"{ $fileName }"

file-received-title = 文件已接收

received-file-via-filerequest =
    通过"{ $requestName }"从未知发送者接收到大小为{ $fileSizeValue } { $fileSizeUnit }的文件"{ $fileName }"

service-channel-name = 服务持久性

service-persistent-running = Fyles 需要保持运行，以便随时发送和接收文件

service-persistent-starting = Fyles 正在启动

service-persistent-title = Fyles 正在运行

service-persistent-waiting-storage = 正在等待存储目录设置...

