# Generated by platform translation tool
# Fluent localization file

file-received-channel-name = 接收的檔案

file-received-mess-with-contact =
    { $senderName } 通過 "{ $requestName }" 發送了大小為 { $fileSizeValue } { $fileSizeUnit } 的文件 "{ $fileName }"

file-received-title = 檔案已接收

received-file-via-filerequest =
    從未知發件人通過"{ $requestName }"接收到大小為{ $fileSizeValue } { $fileSizeUnit }的文件"{ $fileName }"

service-channel-name = 服務持續性

service-persistent-running = Fyles 需要保持運行，以便隨時發送和接收文件

service-persistent-starting = Fyles 正在啟動

service-persistent-title = Fyles 正在運行

service-persistent-waiting-storage = 等待設置存儲目錄...

